version: "3"
services:
  nest:
    build:
      context: ./docker/app/
    container_name: nest
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf
    tty: true
