version: '3'
services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile.app.dev
    container_name: nest
    volumes:
      - .:/app
    ports:
      - 3000:3000
    tty: true
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf
    tty: true
